### ISSUE TITLE
Any chance to add item rename color code support?

### ISSUE THREAD

**Issue by MCwindTIM** [alexcrea/CustomAnvil#18]
Suggest add item rename with color code support as this plugin doesn't works with AnvilColors.

This plugin is excellent for me to customize enchantment but I would like to see if I can rename item with color code.

**Comment by alexcrea** [comment]
Should be able to add it. ETA of 1-2 day if everything go as planned. 
I can do a fast build with color code support if you need it (I will not do it if not asked for)

**Comment by MCwindTIM** [comment]
yes, I would like to have a fast build version. Thanks!

**Comment by alexcrea** [comment]
> yes, I would like to have a fast build version. Thanks!

Code color now work on this [beta version](https://github.com/alexcrea/CustomAnvil/releases/tag/v1.5.4-beta.1).
I continue to implement it on newer version and recommend to updated to 1.5.4 when it will be released.

Currently, you do not need permission to use color, but it is planned to. It will be toggleable so you will be able to disable it (and you can already add `permission_needed_for_color: false` in config.yml if you like to just update and not be annoyed by changes)

**Comment by alexcrea** [comment]
@MCwindTIM Hexadecimal color, color cost (default 0) and usage of permission (can be disabled) was added on the [Latest Release](https://github.com/alexcrea/CustomAnvil/releases/tag/v1.5.4). 
If you like any of the previously mentioned features, you can update.  
If you do update, I recommend checking the basic config interface to check if new configuration options are configured as you like to us them.
