### ISSUE TITLE
Creating custom recipe does not respond to chat input

### ISSUE THREAD

**Issue by galennare** [alexcrea/CustomAnvil#20]
If you use /configanvil to open the GUI and create a custom recipe, and click new, it asks you to type the name of the recipe in chat. Is it impossible to proceed because typing in chat does not do anything and sends the message as normal. Even typing "cancel" does not return the player to the config menu. This does not trigger an exception in the server log either.

**Comment by galennare** [comment]
Not present when CustomAnvil is the only plugin installed. Likely a plugin event conflict.

**Comment by alexcrea** [comment]
> Not present when CustomAnvil is the only plugin installed. Likely a plugin event conflict.

Hi ! I prefer to avoid having conflict. If you have an idea of what plugin if conflicting with Custom Anvil fell free to reopen this issue and tell me as I may be able to resolve it (no guaranty).
