### ISSUE TITLE
Problem about enchanting items

### ISSUE THREAD

**Issue by craftmcpro** [alexcrea/CustomAnvil#24]
Hello, sorry for the inconvenience but your Discord Invite Link isn't working, it's expired or something, I don't know exactly.
I'm testing some enchanting stuff with the server Owner, and we can't get the plugin working properly. Every time we try enchanting ANY enchant, it doesn't work, it instantly closes the anvil menu, giving us the item back, and the enchantment, sometimes it even takes our XP from the inventory without actually enchanting the item.

https://www.youtube.com/watch?v=_3XmvcMAMuI

This is an example of what I am talking about, can we somehow contact you on Discord? Try fixing the invite link to the support server please so we can fix this "bug", if I can call this a bug, thanks!

**Comment by alexcrea** [comment]
I'm sorry I did forget to change the invitation expiration link. It is now fixed.

The issue look like a plugin incompatibility with Custom Anvil.
Do you have any log on your console ?

**Comment by craftmcpro** [comment]
Thanks for the fast response! We have talked on Discord about this problem if anybody needs support!
