### ISSUE TITLE
Incompatible with Disenchantment

### ISSUE THREAD

**Issue by Pandemonious** [alexcrea/CustomAnvil#25]
Is it possible for the different components of this plugin to be disabled?

I like the mechanic for the "too expensive" bypass, but it overrides purpur's "allow-higher-enchants-levels" setting, and makes HTKZ's Disenchantment unusable.

**Comment by alexcrea** [comment]
Hi. Sadly, by how custom anvil is implemented, it kind of can't "just disable" some part (outside what custom anvil provide as config and compatibility components).

For "allow-higher-enchants-levels" custom anvil has it own system where you can set a specific max level enchantment for every enchantment.
To replicate purpur setting: you can set `default_limit: 1000` and remove every element of `enchant_limits` (config.yml) (at least from how I understand the purpur settings)
Tell me if you have any idea how to warn correctly purpur user and maybe an easy migration interface. (other purpur anvil setting are probably affected).

I may have an idea how to make custom anvil compatible with HTKZ's Disenchantment. It may just not work or be more complex than what I'm thinking. No eta & no guaranty.

I could also probably make a plugin with the only job to remove "too expensive" and would be compatible with HTKZ's Disenchantment (and other plugin using the anvil)

**Comment by alexcrea** [comment]
> Is it possible for the different components of this plugin to be disabled?
> 
> I like the mechanic for the "too expensive" bypass, but it overrides purpur's "allow-higher-enchants-levels" setting, and makes HTKZ's Disenchantment unusable.

Hey, I'm still working on making custom anvil "Override Too Expensive" work with Disenchantment. (may release soon).
But it looks [newer version of Disenchantment](https://github.com/H7KZ/Disenchantment/releases/latest) work well with Custom Anvil on my test server. Can you test it with Custom Anvil and tell me if you find any issue (and what do not work) ?

**Comment by alexcrea** [comment]
Should be fixed [on 1.6.0](https://github.com/alexcrea/CustomAnvil/releases).
Please ensure you are also using the latest version of [Disenchantment](https://github.com/H7KZ/Disenchantment/releases/latest)

And if you encounter any other issue, please notify it.

**Comment by Pandemonious** [comment]
Its working now :)
