### ISSUE TITLE
Excellentenchants not working with vanila overlvl

### ISSUE THREAD

**Issue by makegodhere** [alexcrea/CustomAnvil#36]
1. only vanilla overlvl - all good
![image](https://github.com/user-attachments/assets/ce3b85f6-0905-4b01-b3a0-bc88bd001eb7)
![image](https://github.com/user-attachments/assets/6d43f22f-36fa-4247-9ccb-59cc59006d43)
![image](https://github.com/user-attachments/assets/5fb34bd9-c9ae-4029-9f6c-d1e2fc4486d2)
![image](https://github.com/user-attachments/assets/3bd06cc2-aaab-470e-93d7-6f636d4993d2)

2. but if item has any Excellentenchant (Ender Bow on screen for example) - all broken
![image](https://github.com/user-attachments/assets/4a45be72-c8ce-403c-a051-a3f6f6b6d9cc)
![image](https://github.com/user-attachments/assets/4288c642-adf6-479b-a2d7-50372903af0c)
![image](https://github.com/user-attachments/assets/bef91c47-ede5-4e28-b13e-d307e2d2cecc)

**Comment by alexcrea** [comment]
Could replicate the issue and have an idea where this could happen, but not a clear idea how to fix it.
Will try to fix it after uni

**Comment by makegodhere** [comment]
> Could replicate the issue and have an idea where this could happen, but not a clear idea how to fix it. Will try to fix it after uni

for now i found how to bypass this
separate item enchantments (using Disenchantment plugin) to vanilla and Excellentenchants two books
first apply vanilla overlvl and then add Excellentenchants

but so sad doing this every time when i need to add vanilla overlvl enchs ='(

**Comment by alexcrea** [comment]
Fixed on 1.6.6. uploading it on spigot, modrinth & hangar
